name: n8n-workflow-browser
services:
  - name: web
    source_dir: /
    github:
      repo: Harshabyte/ZeroTask-Ai
      branch: main
      deploy_on_push: true
    run_command: python api_server.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    envs:
      - key: PORT
        value: "8000"
      - key: HOST
        value: "0.0.0.0"
      - key: WORKFLOW_DB_PATH
        value: "workflows.db"
